[package]
name = "git-actions"
version = "0.1.0"
edition = "2021"
description = "A Rust-based automation tool for Git events"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
# HTTP server
axum = { version = "0.7", features = ["macros"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Async runtime
tokio = { version = "1.28", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tracing-serde = "0.2"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Config
clap = { version = "4.2", features = ["derive"] }
tempfile = "3.19.0"
