# Server configuration for Git-Actions
apiVersion: "git-actions/v1"
kind: "ServerConfig"

# Server specification
spec:
  port: 8080                # Port number for the HTTP server
  host: "0.0.0.0"           # Host binding address
  
  tls:                      # Optional TLS configuration
    enabled: false
    cert_file: "/path/to/cert.pem"
    key_file: "/path/to/key.pem"
  
  logging:
    level: "INFO"           # Log level: ERROR, WARN, INFO, DEBUG, TRACE
    format: "json"          # Log format: text, json, structured
    file: "/var/log/git-actions.log" # Optional log file
    
  rule_configs:             # Array of additional rule configuration files to load
    - "/path/to/rules/project-a-config.yaml"
    - "/path/to/rules/project-b-config.yaml"
    - "./rules/common-config.yaml"
