# Git-Actions rules configuration for Project B
apiVersion: git-actions/v1
kind: RulesConfig

# Configuration specification
spec:
  webhooks:
    - path: "/gitlab-also"
      type: "gitlab"
      secretFromEnv: "GITLAB_TOKEN"
    
    - path: "/bitbucket"
      type: "bitbucket"
      secretFromEnv: "BITBUCKET_SECRET"
  
  rules:
    # Example rule: Build Docker image on Dockerfile changes
    - name: "docker-build"
      description: "Build Docker image when Dockerfile changes"
      event_types:
        - "push"
        - "pull_request.merged"
      branches:
        - exact: "main"
        - exact: "develop"
      paths:
        - exact: "project-b/Dockerfile"
        - pattern: "project-b/docker/**/*"
      actions:
        - type: "shell"
          command: "cd project-b && docker build -t project-b:latest ."
          working_dir: "./projects"
    
    # Example rule: Run linting on PR
    - name: "lint-code"
      description: "Run linting when a PR is created or updated"
      event_types:
        - "pull_request.opened"
        - "pull_request.updated"
      paths:
        - pattern: "project-b/**/*.js"
        - pattern: "project-b/**/*.ts"
      actions:
        - http:
            method: "POST"
            url: "http://localhost:18080/webhook/github"
            headers:
              "Content-Type": "application/json"
            body: |
              {
                "event": "pull_request",
                "action": "opened",
                "pull_request": {
                  "number": 123,
                  "title": "Test PR",
                  "body": "This is a test PR",
                  "head": {
                    "ref": "feature/test-pr",
                    "sha": "1234567890abcdef"
                  },
                  "base": {
                    "ref": "main",
                    "sha": "fedcba0987654321"
                  }
                }